/**********************************************************************
FORMULA NAME: GB_CMP_INCRM_MERITO_MIN
CREATED_BY : IT-GLOBAL
CREATION_DATE : 07 de Abril del 2026
LAST_UPDATE_DATE : 07 de Abril del 2026
FORMULA TYPE : Compensation Default and Override
DESCRIPTION : Obtiene el porcentaje minimo de incremento por merito
**********************************************************************/

INPUTS ARE CMP_IV_PLAN_START_DATE (text),
CMP_IV_PLAN_END_DATE (text),
CMP_IVR_ASSIGNMENT_ID(NUMBER_NUMBER),
CMP_IV_PLAN_EXTRACTION_DATE (text)

DEFAULT_DATA_VALUE FOR CMP_EXTERNAL_WORKER_DATA_RGE_ASG_VALUE1 IS 'N/A'
DEFAULT_DATA_VALUE FOR CMP_EXTERNAL_WORKER_DATA_RGE_ASG_SEQUENCE_NUMBER IS 0
DEFAULT_DATA_VALUE FOR CMP_EXTERNAL_WORKER_DATA_RGE_ASG_ASSIGNMENT_ID IS 0
DEFAULT_DATA_VALUE FOR CMP_EXTERNAL_WORKER_DATA_RGE_ASG_VALUE2 IS 'N/A'
DEFAULT FOR PER_ASG_ATTRIBUTE1 IS 'PERMANENTE'
DEFAULT FOR PER_ASG_ACTION_CODE IS 'N/A'
DEFAULT FOR CMP_ASSIGNMENT_SALARY_COMPARATIO IS 1

HR_EXTRACT_DATE = TO_DATE(CMP_IV_PLAN_EXTRACTION_DATE, 'YYYY/MM/DD')
l_log = SET_LOG('*** INICIO GB_CMP_INCRM_MERITO_MIN ***')
L_ASG_ID = CMP_IVR_ASSIGNMENT_ID[1]
l_log = SET_LOG('Assignment ID: ' || TO_CHAR(L_ASG_ID))

L_PROM = TO_NUMBER(GET_TABLE_VALUE('GB_INCREMENTO_MERITO_V2', 'Incremento_Promedio', 'BR'))
l_log = SET_LOG('Promedio BR: ' || TO_CHAR(L_PROM))

L_EVAL_TXT = 'N/A'
L_EVAL_MAPPED = 'N/A'
L_IDX = 0

CHANGE_CONTEXTS(EFFECTIVE_DATE = HR_EXTRACT_DATE, COMPENSATION_RECORD_TYPE = 'CMP_MERITO')
(
    L_IDX = CMP_EXTERNAL_WORKER_DATA_RGE_ASG_SEQUENCE_NUMBER.LAST(-1)
    WHILE L_IDX >= 1 LOOP
    (
        L_EXT_VAL = CMP_EXTERNAL_WORKER_DATA_RGE_ASG_VALUE1[L_IDX]
        IF L_EXT_VAL != 'N/A' THEN
        (
            L_EVAL_MAPPED = GET_TABLE_VALUE('GB_CMP_CALIFICAC_MERITO', 'Calificacion_Texto', L_EXT_VAL)
            IF L_EVAL_MAPPED != 'N/A' THEN
            (
                L_EVAL_TXT = L_EVAL_MAPPED
                L_IDX = 0
            )
            ELSE
                L_IDX = L_IDX - 1
        )
        ELSE
            L_IDX = L_IDX - 1
    )
)
l_log = SET_LOG('Evaluacion: ' || L_EVAL_TXT)

CHANGE_CONTEXTS(EFFECTIVE_DATE = HR_EXTRACT_DATE)
(
    L_TIPO_CONTRATO = PER_ASG_ATTRIBUTE1
    L_ACTION = PER_ASG_ACTION_CODE
    L_APERTURA = CMP_ASSIGNMENT_SALARY_COMPARATIO
)
l_log = SET_LOG('Apertura: ' || TO_CHAR(L_APERTURA))

IF L_ACTION = 'HIRE' OR L_ACTION = 'ADD_ASSIGN' THEN
    L_CONDICION = 'New Hire'
ELSE IF L_ACTION = 'PROMOTE' OR L_ACTION = 'PROMOTION' THEN
    L_CONDICION = 'Promotion'
ELSE IF L_TIPO_CONTRATO = '2' THEN
    L_CONDICION = 'Non-permanent contract'
ELSE
    L_CONDICION = 'None'

IF L_CONDICION = 'Promotion' THEN
    L_CLAVE = 'Promotion'
ELSE IF L_CONDICION = 'Non-permanent contract' THEN
    L_CLAVE = 'Non-permanent contract'
ELSE IF L_CONDICION = 'New Hire' THEN
    L_CLAVE = 'New Hire'
ELSE IF L_EVAL_TXT = 'Sobresaliente' AND L_APERTURA <= 100 THEN
    L_CLAVE = 'Sobresaliente_LT100'
ELSE IF L_EVAL_TXT = 'Sobresaliente' AND L_APERTURA > 100 THEN
    L_CLAVE = 'Sobresaliente_GE100'
ELSE IF L_APERTURA < 100 THEN
    L_CLAVE = L_EVAL_TXT || '_LT100'
ELSE
    L_CLAVE = L_EVAL_TXT || '_GE100'

L_RANGO_MIN = GET_TABLE_VALUE('GB_CMP_RANGOS_MERITO', 'Rango_Min', L_CLAVE)
l_log = SET_LOG('Rango Min: ' || L_RANGO_MIN)

IF L_PROM > 10 THEN
(
    L_MIN_R1 = L_PROM - 3
    L_MIN_R2 = L_PROM - 1.5
    L_MIN_R3 = L_PROM
    L_MIN_R4 = L_PROM + 1.5
)
ELSE IF L_PROM >= 5 AND L_PROM <= 10 THEN
(
    L_MIN_R1 = L_PROM * 0.70
    L_MIN_R2 = L_PROM * 0.85
    L_MIN_R3 = L_PROM
    L_MIN_R4 = L_PROM * 1.15
)
ELSE
(
    L_MIN_R1 = L_PROM - 1.5
    L_MIN_R2 = L_PROM - 0.75
    L_MIN_R3 = L_PROM
    L_MIN_R4 = L_PROM + 0.75
)

IF L_RANGO_MIN = 'NO' THEN
    L_DEFAULT_MIN = 0
ELSE IF L_RANGO_MIN = 'R1' THEN
    L_DEFAULT_MIN = L_MIN_R1
ELSE IF L_RANGO_MIN = 'R2' THEN
    L_DEFAULT_MIN = L_MIN_R2
ELSE IF L_RANGO_MIN = 'R3' THEN
    L_DEFAULT_MIN = L_MIN_R3
ELSE IF L_RANGO_MIN = 'R4' THEN
    L_DEFAULT_MIN = L_MIN_R4
ELSE IF L_RANGO_MIN = 'PROM' THEN
    L_DEFAULT_MIN = 0
ELSE
    L_DEFAULT_MIN = 0

l_log = SET_LOG('*** RESULTADO MIN: ' || TO_CHAR(L_DEFAULT_MIN) || ' ***')
RETURN L_DEFAULT_MIN